### ISSUE TITLE
package arjuna/middleware is not in GOROOT (/usr/local/go/src/arjuna/middleware)

### ISSUE THREAD

**Issue by priambudiLB** [arjuna-chatbot/arjuna#2]
Error: package arjuna/middleware is not in GOROOT (/usr/local/go/src/arjuna/middleware) when building docker image

**Comment by hashlash** [comment]
Btw, when using go modules, you could import the packages using the repo URL as the import prefix.

Example for `arjuna/middleware`:

```go
import "github.com/arjuna-chatbot/arjuna/middleware"
```
